name: CBSSAFETYGEAR
favicon: null
layout_spectrum: 0.49871
typography_spectrum: 0.11586535722017288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d3dbde'
    - '#787a7c'
    - '#403c34'
  brandStrength: 0.04900242201983929
  lightness: 0.375
  saturation: 0.3007449477445334
  rhythmicContrast: 0
purpose: []
